# Generated by Django 5.2 on 2025-04-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_alter_event_plant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="pot_size",
        ),
        migrations.AlterField(
            model_name="plant",
            name="light",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Direct sunlight"),
                    (2, "Bright indirect sunlight"),
                    (3, "Indirect sunlight"),
                    (4, "Half-shadow"),
                    (5, "Shadow"),
                ]
            ),
        ),
    ]
