# Generated by Django 5.2 on 2025-04-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0008_imageupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageUpload",
        ),
    ]
