# Generated by Django 5.2 on 2025-05-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0009_delete_imageupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotes",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Unknown"), (1, "User"), (2, "AI")], default=0
            ),
        ),
    ]
