# Generated by Django 5.2 on 2025-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0012_watering"),
    ]

    operations = [
        migrations.AddField(
            model_name="airating",
            name="note",
            field=models.TextField(default=""),
        ),
    ]
