# Generated by Django 5.2 on 2025-05-03 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0014_remove_usernotes_type_watering_next_watering"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="watering_frequency",
            field=models.IntegerField(
                default=3, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
