# Generated by Django 5.2 on 2025-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0015_plant_watering_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watering",
            name="next_watering",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
