# Generated by Django 5.2 on 2025-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0016_alter_watering_next_watering"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantTips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tip", models.TextField()),
            ],
        ),
    ]
