# Generated by Django 5.2 on 2025-05-04 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0017_planttips"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownedplants",
            name="owner_watering_frequency",
            field=models.IntegerField(
                default=3, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
