# Generated by Django 5.2 on 2025-05-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0019_userlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantdetailcomments",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
