# Generated by Django 5.2 on 2025-05-11 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0020_alter_plantdetailcomments_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownedplants",
            name="owner_watering_frequency",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
