# Generated by Django 5.2 on 2025-05-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0021_alter_ownedplants_owner_watering_frequency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ownedplants",
            options={"permissions": [("can_diagnose", "Can diagnose plants")]},
        ),
    ]
