# Generated by Django 5.2 on 2025-05-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0022_alter_ownedplants_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlantUserPhotos",
        ),
    ]
