# Generated by Django 5.2 on 2025-05-17 15:34

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0023_delete_plantuserphotos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlocation",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="", max_length=100, null=True
            ),
        ),
    ]
